### ISSUE TITLE
Hỏi về sử dụng tvietlistings.sty

### ISSUE THREAD

**Issue by quanhinh9** [thiminhnhut/latex#1]
Xin cho hỏi khi sử dụng tvietlistings.sty mình thấy báo lỗi ở dòng 26:

Undefined control sequence. \lstset

Làm sao sửa được lỗi này ạ?

**Comment by thiminhnhut** [comment]
Bạn import các package theo thứ tự này thì package `tvietlistings.sty` (khai báo package `listings.sty` trước) mới nhận được lệnh `\lstset`:
```tex
\usepackage[vietnamese.licr]{babel}
\usepackage{listings}
\usepackage{tvietlistings}
```
